spring.application.name=${SPRING_APPLICATION_NAME:SpringDocker}
server.port=${SERVER_PORT:8080}


jwt.secret_key=${JWT_SECRET_KEY}
jwt.expiration.time=${JWT_EXPIRATION_TIME:86400000}

spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8

# Actuator configuration for healthcheck
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
management.health.defaults.enabled=true